### ISSUE TITLE
There's no way to overwrite files if they exist

### ISSUE THREAD

**Issue by FdelMazo** [aTable/deploy-to-dropbox#6]
Currently, the action only uploads files in the mode "add", which tries to append stuff to a file if it already exists. It would be really good if it also had support for the "rename" and "overwrite" modes

**Comment by aTable** [comment]
This is intentional so that the prototype didn't cause data loss. As I don't actually use dropbox myself, I have no intention to implement this however, it looks like people have forked this and extended further.

[This fork](https://github.com/rensatsu/deploy-to-dropbox) looks promising
