### ISSUE TITLE
add a sample please

### ISSUE THREAD

**Issue by easa** [aTable/deploy-to-dropbox#7]

**Comment by maksimonishchenko** [comment]
yes please

**Comment by aTable** [comment]
Bit vague on details here, can you be more specific? I think this is already done 

- [sample markdown inputs](https://github.com/aTable/deploy-to-dropbox/tree/master/sample)
- [used in the action](https://github.com/aTable/deploy-to-dropbox/blob/master/.github/workflows/main.yml)
- results in action [saving file to dropbox](https://github.com/aTable/deploy-to-dropbox/runs/7224529372?check_suite_focus=true#step:3:12)
